--- #YAML:1.0
name:               App-RecordStream
version:            3.5
abstract:           System for commandline analysis of data
author:
    - Ben Bernard - perlhacker@benjaminbernard.com Keith Amling - keith.amling@gmail.com
license:            MIT
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:                 0
    Date::Manip:          0
    DBD::SQLite:          0
    DBI:                  0
    File::Temp:           0
    FindBin:              0
    Getopt::Long:         0
    HTTP::Request:        0
    IO::String:           0
    JSON:                 0
    JSON::XS:             0
    LWP:                  0
    Net::DNS::Packet:     0
    Net::Pcap:            0
    NetPacket::Ethernet:  0
    Proc::ProcessTable:   0
    Test::More:           0
    Text::CSV:            0
    Tie::IxHash:          0
    XML::Simple:          0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
