---
abstract: 'System for commandline analysis of data'
author:
  - 'Ben Bernard - perlhacker@benjaminbernard.com Keith Amling - keith.amling@gmail.com'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.140640'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: App-RecordStream
no_index:
  directory:
    - t
    - inc
requires:
  Carp: '0'
  DBD::SQLite: '0'
  DBI: '0'
  Data::Dumper: '0'
  Date::Manip: '0'
  File::Temp: '0'
  FindBin: '0'
  Getopt::Long: '0'
  HTTP::Request: '0'
  IO::String: '0'
  JSON: '0'
  JSON::XS: '0'
  LWP::UserAgent: '0'
  List::MoreUtils: '0'
  Scalar::Util: '0'
  Term::ReadKey: '0'
  Test::More: '0'
  Text::Autoformat: '0'
  Text::CSV: '0'
  Text::CSV_XS: '0.99'
  Tie::Array: '0'
  Tie::Hash: '0'
  Tie::IxHash: '0'
  XML::Twig: '0'
version: v4.0.7
